package br.com.dbc.vemser.jedimasters.model.entity;

public enum TipoPrint {
    ATAQUE, ATAQUESORT, POCAOUTILIZADA, FIMPOCAODANO, POCAOINEXISTENTE,
    NOMEJOGADOR, ESCOLHAMONSTRO, MONSTRONUM, ESCOLHA1OU2, DERROTA, DERROTAMONSTRO, PROXDEFENSOR, VOLTARMENU, CRIARMONSTRO, LISTARMONSTROS, OPCAOINEXISTENTE, QUANTCARTA, TIPOCARTA, ATRIBUTOATIVOCARTA, CRIARCARTA, LISTARCARTAS, NENHUMACARTA, NENHUMMONSTRO
}
