pipeline {
    agent any

    tools {
        maven 'M3'
    }

    stages {
        stage('1. Preparar Ambiente') {
            steps {
                echo 'Iniciando análise do projeto Java na Parte 2...'
                sh 'ls -R' 
            }
        }

        stage('2. SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarServer') {
                    dir("Parte 2/projeto-java") {
                        sh 'mvn clean compile org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar ' +
                           '-Dsonar.projectKey=projeto-java-augusto ' +
                           '-Dsonar.sources=Elements/src/main/java ' +
                           '-Dsonar.java.binaries=target/classes ' +
                           '-Dmaven.compiler.source=17 ' +
                           '-Dmaven.compiler.target=17'
                    }
                }
            }
        }

        stage("3. Quality Gate") {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
    
    post {
        always {
            echo 'Finalizando execução da Parte 2.'
        }
    }
}