pipeline {
    agent any

    tools {
        maven 'M3'
    }

    stages {
        stage('1. Preparar Ambiente') {
            steps {
                echo 'Iniciando análise do projeto Java na Parte 2...'
                sh 'ls -R' 
            }
        }

        stage('2. SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarServer') {
                    dir("Parte 2/projeto-java") {
                        sh """
                        # 1. Limpeza total e criação da estrutura
                        rm -rf target
                        mkdir -p src/main/java
                        cp -r Elements/src/main/java/* src/main/java/
                        
                        # 2. Comando Maven com 'force update' (-U) e versão do Lombok explícita
                        mvn clean compile org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
                        -U \
                        -Dlombok.version=1.18.24 \
                        -Dsonar.projectKey=projeto-java-augusto \
                        -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }

        stage("3. Quality Gate") {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
    
    post {
        always {
            echo 'Finalizando execução da Parte 2.'
        }
    }
}