pipeline {
    agent any
    
    tools {
        maven 'M3'
    }

    stages {
        stage('1. Checkout Repositorios') {
            steps {
                // 1. O Jenkins já baixou o repositório do Jenkinsfile automaticamente
                echo "Repositório do Jenkinsfile já está pronto."

                // 2. Baixar o projeto Java para dentro da pasta Parte2
                dir('Parte2/projeto-java') {
                    git branch: 'main', 
                        url: 'URL_DO_REPOSITORIO_JAVA_AQUI',
                        credentialsId: 'github-pat-AugustoJBM' 
                }
            }
        }

        stage('2. SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarServer') {
                    // Entramos na pasta onde o projeto Java foi baixado para rodar o Maven
                    dir('Parte2/projeto-java') {
                        sh 'mvn clean verify sonar:sonar -Dsonar.projectKey=projeto-java-augusto'
                    }
                }
            }
        }

        stage("3. Quality Gate") {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}