
CREATE SEQUENCE SEQ_ELEMENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_ELEMENTO;

CREATE TABLE ELEMENTO(
	id_elemento NUMBER NOT NULL,
	nome VARCHAR2(25),
	PRIMARY KEY (id_elemento)
);

DROP TABLE ELEMENTO;

SELECT * FROM ELEMENTO

CREATE SEQUENCE SEQ_MONSTRO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_MONSTRO;

CREATE TABLE MONSTRO(
	id_monstro NUMBER NOT NULL,
	id_elemento NUMBER NOT NULL,
	nome VARCHAR2(50),
	vida NUMBER(4,0),
	danoBase NUMBER(4,0),
	PRIMARY KEY (id_monstro),
	CONSTRAINT FK_ELEMENTO FOREIGN KEY (id_elemento) REFERENCES ELEMENTO(id_elemento)
);

DROP TABLE MONSTRO;

SELECT * FROM MONSTRO

----------------------------------------------------------------------

CREATE SEQUENCE SEQ_JOGADORES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_JOGADORES;

CREATE TABLE JOGADORES(
	id_jogador NUMBER(38),
	nome VARCHAR2(50),
	PRIMARY KEY (id_jogador)
);

SELECT * FROM JOGADORES;

DROP TABLE JOGADORES;

CREATE SEQUENCE SEQ_CARTAS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

DROP SEQUENCE SEQ_CARTAS;

CREATE TABLE CARTAS(
	id_carta NUMBER(38),
	tipo VARCHAR2(10),
	quant NUMBER(4),
	atributoAtivo VARCHAR2(50),
	PRIMARY KEY (id_carta)
);

DROP TABLE CARTAS;

SELECT * FROM CARTAS;